vich_uploader:
    db_driver: orm

    mappings:
        generic_file:
            uri_prefix: /files
            upload_destination: '%kernel.project_dir%/public/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            inject_on_load: false
        conference_logo:
            uri_prefix: /files/logo
            upload_destination: '%kernel.project_dir%/public/files/logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            inject_on_load: false
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
